apiVersion: v1
kind: Config
users:
  - name: my-user
    user:
      exec:
        command: "./client-go-exec-plugin"
        apiVersion: "client.authentication.k8s.io/v1beta1"
        args:
          - "--timeout=10"
          - "--addr=10.1.97.101"
          - "--ws=http://10.254.24.66:8899"
          - "--user=wangshuaijian"
          - "--publickey=/Users/wangshuaijian/go_workspace/src/github.com/jianzi123/awesomeJJ/script/public_key"
          - "--logPath=/Users/wangshuaijian/go_workspace/src/github.com/jianzi123/awesomeJJ/wsj.log"
clusters:
  - name: my-cluster
    cluster:
      insecure-skip-tls-verify: true
      server: https://10.254.24.67:6443
contexts:
  - name: my-cluster
    context:
      cluster: my-cluster
      user: my-user
current-context: my-cluster
